### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by thomasneil** [thomasneil/networks-demo#1]
The current version of the code is very unstructured. Would appreciate if someone could do some html edits to put the visualization in a scaled, centered div

**Comment by Sakura74** [comment]
can you assign this issue to me

**Comment by courtneyoverby** [comment]
I absolutely can take this on. 👍

**Comment by thomasneil** [comment]
> I absolutely can take this on. 👍

Hi Courtney, I'd like to assign this to Sakura74 first? I will be adding more issues that I would appreciate help with

**Comment by Sakura74** [comment]
I have centered the visualization you can have a look and tell if it is ok

**Comment by thomasneil** [comment]
Yes! That works!
